AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  f-app

  Sample SAM Template for f-app

Parameters:
  MasterSecretArn:
    Description: Master Secret ARN
    Type: String
  MasterSecretsManagerKey:
    Description: KMS Key for the use of secrets across accounts
    Type: String
  Stage:
    Description: Environment
    Type: String

  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  LectureFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: dist/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        ListLectures:
          Type: Api 
          Properties:
            Path: /classes
            Method: get
        CreateLectures:
          Type: Api 
          Properties:
            Path: /classes
            Method: post
        GetDetails:
          Type: Api
          Properties:
            Path: /classes/id
            Method: get
        AddCart:
          Type: Api
          Properties:
            Path: /classes/id
            Method: post
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Account function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/account/"
  LectureFunction:
    Description: "Account Lambda Function ARN"
    Value: !GetAtt LectureFunction.Arn
  LectureFunctionIamRole:
    Description: "Implicit IAM Role created for Account function"
    Value: !GetAtt LectureFunction.Arn
