import {
    attribute,
    autoGeneratedHashKey,
    hashKey,
    rangeKey,
    table
} from '@aws/dynamodb-data-mapper-annotations';
import {embed} from '@aws/dynamodb-data-mapper';


// cloudformation template에서 생성되는 TABLE값을 ENV로 받아와 사용 
const tableName: string = String(process.env.SAMPLE_TABLE);

if (!process.env.SAMPLE_TABLE) {
    this.tableName = 'class-dev-LectureTable-MXV4LYH979IN';;
}


@table(tableName)
class LectureEntity {

    //UUIDv4를 통해 autoGenerated 됨
    @autoGeneratedHashKey()
    lectureId: string;

    @rangeKey()
    sortkey?: string;

    @attribute({defaultProvider: () => new Date()})
    createdAt: Date;

    @attribute()
    attribute1?: string;

    @attribute()
    attribute2?: string;

    @attribute()
    lectureNm?: string;             /** 클래스 이름 */

    @attribute()
    lectureStatusCd?: string;       /*  클래스 상태코드 - Y : 접수중 N : 접수 불가 (임시..)*/

    /**
     * 
     */
    public domainlogic(): string {
        this.attribute1 = "1";
        return this.attribute1;
    }

    get toJson(): string {
        return JSON.stringify(this);
    }

    /**
     * 
     * https://github.com/awslabs/dynamodb-data-mapper-js/issues/136
     * @param lectureId 
     * @param sortkey 
     * @param attribute1 
     * @param attribute2
     * @param lectureNm
     * @param lectureStatusCd
     */
    public static createObject(request: LectureEntity): LectureEntity {
        console.log("### object is : ", request);

        //TODO Validation Implementation
        //Example) 강좌제목에 비속어가 들어있다던지? 특정항목이 null이라던지?
        //만약 validation 과정이 길어지면 Domain layer에 Validator로 별도로 분리하는것을 고려할 것 
        return Object.assign(new LectureEntity(),
            {
                // 실제로 클래스를 생성할때, 입력받아야 하는 값들을 추려야함 
                createdAt: new Date(),
                sortkey: request.sortkey,
                attribute1: request.attribute1,
                attribute2: request.attribute2,
                lectureNm: request.lectureNm,
                lectureStatusCd: request.lectureStatusCd
            }
        );
    }

}

export default LectureEntity;